// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background': string;
  'centersubcomp': string;
  'centersubcompSm': string;
}
export const cssExports: CssExports;
export default cssExports;
