// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'responsiveblockimg': string;
  'responsiveinlblockimg': string;
}
export const cssExports: CssExports;
export default cssExports;
