// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'black_overlay': string;
  'loginformdiv': string;
  'loginformdivSm': string;
}
export const cssExports: CssExports;
export default cssExports;
