// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cboxContent': string;
  'forgotPass': string;
  'forgotPassSm': string;
  'linksdiv': string;
  'linksdivSm': string;
  'loginlink': string;
  'xpass': string;
}
export const cssExports: CssExports;
export default cssExports;
